/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppContainer: typeof import('./theme/components/AppContainer.vue')['default']
    DocFooter: typeof import('./theme/components/DocFooter.vue')['default']
    HomePage: typeof import('./theme/components/HomePage.vue')['default']
    Share: typeof import('./theme/components/Share.vue')['default']
    TocList: typeof import('./theme/components/TocList.vue')['default']
  }
}
