# .github/workflows/contributors.yml
jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image_size: 100
  AutoCorrect:
    runs-on: ubuntu-latest
    steps:
      - name: Check source code
        uses: actions/checkout@main

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@main
        with:
          use_npm: true
          args: --fix

name: Contributors

on:
  push:
    branches:
      - main
